### model
model_name_or_path: Qwen/Qwen3-1.7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 4096
lora_alpha: 2048
lora_dropout: 0.05
lora_target: all

### dataset
dataset: pii
template: qwen3
cutoff_len: 2048
max_samples: 400000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /workspace/saves/qwen3-1.7b/lora/sft
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: pii_test
val_size: 0.1
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 5000
